Adding language info and file extension for the spark kernel
jupyter-incubator/sparkmagic pull request #692
Opened 2020-12-14 16:21 UTC by skakker

### Description
The language and file_extension are missing from the spark magic kernel, because of which it has trouble integrating with other features like jupyterlab-lsp. Hence updating the same. 

### Checklist
- [ ] Wrote a description of my changes above 
- [ ] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [ ] Added or modified unit tests to reflect my changes
- [ ] Manually tested with a notebook
- [ ] If adding a feature, there is an example notebook and/or documentation in the `README.md` file

2020-12-14 23:07 UTC, devstein requested changes
Thanks for contributing! Can you also make the change for the [PySpark kernel](https://github.com/jupyter-incubator/sparkmagic/tree/master/sparkmagic/sparkmagic/kernels/pysparkkernel) and provide instructions for how to do a manual test?

2020-12-16 12:08 UTC, skakker commented
Added for Pyspark and R kernel. 
Thanks :)

2020-12-18 17:21 UTC, devstein requested changes
One quick fix

2020-12-18 17:21 UTC, devstein commented on sparkmagic/sparkmagic/kernels/pysparkkernel/pysparkkernel.py
> +            'file_extension': '.py'
Add a `,`

2020-12-20 00:55 UTC, devstein approved these changes

2020-12-20 00:55 UTC, merged